
DELETE http://127.0.0.1:5000/api/v1/books/2
Content-Type: application/json

<!--POST http://127.0.0.1:5000/api/v1/books
Content-Type: application/json

{
    "title": "Test title",
    "author": "Test author"
}-->
